version: '3.4'

services:
  tma.ecommerce.api.customers:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  tma.ecommerce.api.orders:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  tma.ecommerce.api.products:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  tma.ecommerce.api.search:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

